// iso_map.js
export const ISO_COUNTRY_MAP = {
    "af": "Afghanistan","afg": "Afghanistan","afghanistan": "Afghanistan",
    "al": "Albania","alb": "Albania","albania": "Albania",
    "dz": "Algeria","dza": "Algeria","algeria": "Algeria",
    "as": "American Samoa","asm": "American Samoa","american samoa": "American Samoa",
    "ad": "Andorra","and": "Andorra","andorra": "Andorra",
    "ao": "Angola","ago": "Angola","angola": "Angola",
    "ai": "Anguilla","aia": "Anguilla","anguilla": "Anguilla",
    "aq": "Antarctica","ata": "Antarctica","antarctica": "Antarctica",
    "ag": "Antigua and Barbuda","atg": "Antigua and Barbuda","antigua and barbuda": "Antigua and Barbuda",
    "ar": "Argentina","arg": "Argentina","argentina": "Argentina",
    "am": "Armenia","arm": "Armenia","armenia": "Armenia",
    "aw": "Aruba","abw": "Aruba","aruba": "Aruba",
    "au": "Australia","aus": "Australia","australia": "Australia",
    "at": "Austria","aut": "Austria","austria": "Austria",
    "az": "Azerbaijan","aze": "Azerbaijan","azerbaijan": "Azerbaijan",
    "bs": "Bahamas","bhs": "Bahamas","bahamas": "Bahamas",
    "bh": "Bahrain","bhr": "Bahrain","bahrain": "Bahrain",
    "bd": "Bangladesh","bgd": "Bangladesh","bangladesh": "Bangladesh",
    "bb": "Barbados","brb": "Barbados","barbados": "Barbados",
    "by": "Belarus","blr": "Belarus","belarus": "Belarus",
    "be": "Belgium","bel": "Belgium","belgium": "Belgium",
    "bz": "Belize","blz": "Belize","belize": "Belize",
    "bj": "Benin","ben": "Benin","benin": "Benin",
    "bm": "Bermuda","bmu": "Bermuda","bermuda": "Bermuda",
    "bt": "Bhutan","btn": "Bhutan","bhutan": "Bhutan",
    "bo": "Bolivia","bol": "Bolivia","bolivia": "Bolivia",
    "ba": "Bosnia and Herzegovina","bih": "Bosnia and Herzegovina","bosnia and herzegovina": "Bosnia and Herzegovina",
    "bw": "Botswana","bwa": "Botswana","botswana": "Botswana",
    "br": "Brazil","bra": "Brazil","brazil": "Brazil",
    "bn": "Brunei","brn": "Brunei","brunei": "Brunei",
    "bg": "Bulgaria","bgr": "Bulgaria","bulgaria": "Bulgaria",
    "bf": "Burkina Faso","bfa": "Burkina Faso","burkina faso": "Burkina Faso",
    "bi": "Burundi","bdi": "Burundi","burundi": "Burundi",
    "kh": "Cambodia","khm": "Cambodia","cambodia": "Cambodia",
    "cm": "Cameroon","cmr": "Cameroon","cameroon": "Cameroon",
    "ca": "Canada","can": "Canada","canada": "Canada",
    "cv": "Cabo Verde","cpv": "Cabo Verde","cabo verde": "Cabo Verde",
    "ky": "Cayman Islands","cym": "Cayman Islands","cayman islands": "Cayman Islands",
    "cf": "Central African Republic","caf": "Central African Republic","central african republic": "Central African Republic",
    "td": "Chad","tcd": "Chad","chad": "Chad",
    "cl": "Chile","chl": "Chile","chile": "Chile",
    "cn": "China","chn": "China","china": "China",
    "co": "Colombia","col": "Colombia","colombia": "Colombia",
    "km": "Comoros","com": "Comoros","comoros": "Comoros",
    "cg": "Congo","cog": "Congo","congo": "Congo",
    "cd": "Congo (DR)","cod": "Congo (DR)","drc": "Congo (DR)",
    "cr": "Costa Rica","cri": "Costa Rica","costa rica": "Costa Rica",
    "hr": "Croatia","hrv": "Croatia","croatia": "Croatia",
    "cu": "Cuba","cub": "Cuba","cuba": "Cuba",
    "cy": "Cyprus","cyp": "Cyprus","cyprus": "Cyprus",
    "cz": "Czechia","cze": "Czechia","czechia": "Czechia","czech republic": "Czechia",
    "dk": "Denmark","dnk": "Denmark","denmark": "Denmark",
    "dj": "Djibouti","dji": "Djibouti","djibouti": "Djibouti",
    "dm": "Dominica","dma": "Dominica","dominica": "Dominica",
    "do": "Dominican Republic","dom": "Dominican Republic","dominican republic": "Dominican Republic",
    "ec": "Ecuador","ecu": "Ecuador","ecuador": "Ecuador",
    "eg": "Egypt","egy": "Egypt","egypt": "Egypt",
    "sv": "El Salvador","slv": "El Salvador","el salvador": "El Salvador",
    "gq": "Equatorial Guinea","gnq": "Equatorial Guinea","equatorial guinea": "Equatorial Guinea",
    "er": "Eritrea","eri": "Eritrea","eritrea": "Eritrea",
    "ee": "Estonia","est": "Estonia","estonia": "Estonia",
    "sz": "Eswatini","swz": "Eswatini","swaziland": "Eswatini",
    "et": "Ethiopia","eth": "Ethiopia","ethiopia": "Ethiopia",
    "fj": "Fiji","fji": "Fiji","fiji": "Fiji",
    "fi": "Finland","fin": "Finland","finland": "Finland",
    "fr": "France","fra": "France","france": "France",
    "ga": "Gabon","gab": "Gabon","gabon": "Gabon",
    "gm": "Gambia","gmb": "Gambia","gambia": "Gambia",
    "ge": "Georgia","geo": "Georgia","georgia": "Georgia",
    "de": "Germany","deu": "Germany","germany": "Germany",
    "gh": "Ghana","gha": "Ghana","ghana": "Ghana",
    "gi": "Gibraltar","gib": "Gibraltar","gibraltar": "Gibraltar",
    "gr": "Greece","grc": "Greece","greece": "Greece",
    "gl": "Greenland","grl": "Greenland","greenland": "Greenland",
    "gd": "Grenada","grd": "Grenada","grenada": "Grenada",
    "gp": "Guadeloupe","glp": "Guadeloupe","guadeloupe": "Guadeloupe",
    "gu": "Guam","gum": "Guam","guam": "Guam",
    "gt": "Guatemala","gtm": "Guatemala","guatemala": "Guatemala",
    "gn": "Guinea","gin": "Guinea","guinea": "Guinea",
    "gw": "Guinea-Bissau","gnb": "Guinea-Bissau","guinea-bissau": "Guinea-Bissau",
    "gy": "Guyana","guy": "Guyana","guyana": "Guyana",
    "ht": "Haiti","hti": "Haiti","haiti": "Haiti",
    "hn": "Honduras","hnd": "Honduras","honduras": "Honduras",
    "hk": "Hong Kong","hkg": "Hong Kong","hong kong": "Hong Kong",
    "hu": "Hungary","hun": "Hungary","hungary": "Hungary",
    "is": "Iceland","isl": "Iceland","iceland": "Iceland",
    "in": "India","ind": "India","india": "India",
    "id": "Indonesia","idn": "Indonesia","indonesia": "Indonesia",
    "ir": "Iran","irn": "Iran","iran": "Iran",
    "iq": "Iraq","irq": "Iraq","iraq": "Iraq",
    "ie": "Ireland","irl": "Ireland","ireland": "Ireland",
    "il": "Israel","isr": "Israel","israel": "Israel",
    "it": "Italy","ita": "Italy","italy": "Italy",
    "jm": "Jamaica","jam": "Jamaica","jamaica": "Jamaica",
    "jp": "Japan","jpn": "Japan","japan": "Japan",
    "jo": "Jordan","jor": "Jordan","jordan": "Jordan",
    "kz": "Kazakhstan","kaz": "Kazakhstan","kazakhstan": "Kazakhstan",
    "ke": "Kenya","ken": "Kenya","kenya": "Kenya",
    "kp": "North Korea","prk": "North Korea","north korea": "North Korea",
    "kr": "South Korea","kor": "South Korea","south korea": "South Korea",
    "kw": "Kuwait","kwt": "Kuwait","kuwait": "Kuwait",
    "kg": "Kyrgyzstan","kgz": "Kyrgyzstan","kyrgyzstan": "Kyrgyzstan",
    "la": "Laos","lao": "Laos","laos": "Laos",
    "lv": "Latvia","lva": "Latvia","latvia": "Latvia",
    "lb": "Lebanon","lbn": "Lebanon","lebanon": "Lebanon",
    "ls": "Lesotho","lso": "Lesotho","lesotho": "Lesotho",
    "lr": "Liberia","lbr": "Liberia","liberia": "Liberia",
    "ly": "Libya","lby": "Libya","libya": "Libya",
    "li": "Liechtenstein","lie": "Liechtenstein","liechtenstein": "Liechtenstein",
    "lt": "Lithuania","ltu": "Lithuania","lithuania": "Lithuania",
    "lu": "Luxembourg","lux": "Luxembourg","luxembourg": "Luxembourg",
    "mo": "Macau","mac": "Macau","macau": "Macau",
    "mg": "Madagascar","mdg": "Madagascar","madagascar": "Madagascar",
    "mw": "Malawi","mwi": "Malawi","malawi": "Malawi",
    "my": "Malaysia","mys": "Malaysia","malaysia": "Malaysia",
    "mv": "Maldives","mdv": "Maldives","maldives": "Maldives",
    "ml": "Mali","mli": "Mali","mali": "Mali",
    "mt": "Malta","mlt": "Malta","malta": "Malta",
    "mh": "Marshall Islands","mhl": "Marshall Islands","marshall islands": "Marshall Islands",
    "mq": "Martinique","mtq": "Martinique","martinique": "Martinique",
    "mr": "Mauritania","mrt": "Mauritania","mauritania": "Mauritania",
    "mu": "Mauritius","mus": "Mauritius","mauritius": "Mauritius",
    "yt": "Mayotte","myt": "Mayotte","mayotte": "Mayotte",
    "mx": "Mexico","mex": "Mexico","mexico": "Mexico",
    "fm": "Micronesia","fsm": "Micronesia","micronesia": "Micronesia",
    "md": "Moldova","mda": "Moldova","moldova": "Moldova",
    "mc": "Monaco","mco": "Monaco","monaco": "Monaco",
    "mn": "Mongolia","mng": "Mongolia","mongolia": "Mongolia",
    "me": "Montenegro","mne": "Montenegro","montenegro": "Montenegro",
    "ms": "Montserrat","msr": "Montserrat","montserrat": "Montserrat",
    "ma": "Morocco","mar": "Morocco","morocco": "Morocco",
    "mz": "Mozambique","moz": "Mozambique","mozambique": "Mozambique",
    "mm": "Myanmar","mmr": "Myanmar","myanmar": "Myanmar","burma": "Myanmar",
    "na": "Namibia","nam": "Namibia","namibia": "Namibia",
    "nr": "Nauru","nru": "Nauru","nauru": "Nauru",
    "np": "Nepal","npl": "Nepal","nepal": "Nepal",
    "nl": "Netherlands","nld": "Netherlands","netherlands": "Netherlands",
    "nc": "New Caledonia","ncl": "New Caledonia","new caledonia": "New Caledonia",
    "nz": "New Zealand","nzl": "New Zealand","new zealand": "New Zealand",
    "ni": "Nicaragua","nic": "Nicaragua","nicaragua": "Nicaragua",
    "ne": "Niger","ner": "Niger","niger": "Niger",
    "ng": "Nigeria","nga": "Nigeria","nigeria": "Nigeria",
    "nu": "Niue","niu": "Niue","niue": "Niue",
    "nf": "Norfolk Island","nfk": "Norfolk Island","norfolk island": "Norfolk Island",
    "mk": "North Macedonia","mkd": "North Macedonia","north macedonia": "North Macedonia",
    "mp": "Northern Mariana Islands","mnp": "Northern Mariana Islands",
    "no": "Norway","nor": "Norway","norway": "Norway",
    "om": "Oman","omn": "Oman","oman": "Oman",
    "pk": "Pakistan","pak": "Pakistan","pakistan": "Pakistan",
    "pw": "Palau","plw": "Palau","palau": "Palau",
    "pa": "Panama","pan": "Panama","panama": "Panama",
    "pg": "Papua New Guinea","png": "Papua New Guinea","papua new guinea": "Papua New Guinea",
    "py": "Paraguay","pry": "Paraguay","paraguay": "Paraguay",
    "pe": "Peru","per": "Peru","peru": "Peru",
    "ph": "Philippines","phl": "Philippines","philippines": "Philippines",
    "pl": "Poland","pol": "Poland","poland": "Poland",
    "pt": "Portugal","prt": "Portugal","portugal": "Portugal",
    "pr": "Puerto Rico","pri": "Puerto Rico","puerto rico": "Puerto Rico",
    "qa": "Qatar","qat": "Qatar","qatar": "Qatar",
    "re": "Reunion","reu": "Reunion","reunion": "Reunion",
    "ro": "Romania","rou": "Romania","romania": "Romania",
    "ru": "Russia","rus": "Russia","russia": "Russia",
    "rw": "Rwanda","rwa": "Rwanda","rwanda": "Rwanda",
    "sh": "Saint Helena","shn": "Saint Helena","saint helena": "Saint Helena",
    "kn": "Saint Kitts and Nevis","kna": "Saint Kitts and Nevis","saint kitts and nevis": "Saint Kitts and Nevis",
    "lc": "Saint Lucia","lca": "Saint Lucia","saint lucia": "Saint Lucia",
    "pm": "Saint Pierre and Miquelon","spm": "Saint Pierre and Miquelon",
    "vc": "Saint Vincent and the Grenadines","vct": "Saint Vincent and the Grenadines",
    "ws": "Samoa","wsm": "Samoa","samoa": "Samoa",
    "sm": "San Marino","smr": "San Marino","san marino": "San Marino",
    "st": "Sao Tome and Principe","stp": "Sao Tome and Principe",
    "sa": "Saudi Arabia","sau": "Saudi Arabia","saudi arabia": "Saudi Arabia",
    "sn": "Senegal","sen": "Senegal","senegal": "Senegal",
    "rs": "Serbia","srb": "Serbia","serbia": "Serbia",
    "sc": "Seychelles","syc": "Seychelles","seychelles": "Seychelles",
    "sl": "Sierra Leone","sle": "Sierra Leone","sierra leone": "Sierra Leone",
    "sg": "Singapore","sgp": "Singapore","singapore": "Singapore",
    "sk": "Slovakia","svk": "Slovakia","slovakia": "Slovakia",
    "si": "Slovenia","svn": "Slovenia","slovenia": "Slovenia",
    "sb": "Solomon Islands","slb": "Solomon Islands","solomon islands": "Solomon Islands",
    "so": "Somalia","som": "Somalia","somalia": "Somalia",
    "za": "South Africa","zaf": "South Africa","south africa": "South Africa",
    "ss": "South Sudan","ssd": "South Sudan","south sudan": "South Sudan",
    "es": "Spain","esp": "Spain","spain": "Spain",
    "lk": "Sri Lanka","lka": "Sri Lanka","sri lanka": "Sri Lanka",
    "sd": "Sudan","sdn": "Sudan","sudan": "Sudan",
    "sr": "Suriname","sur": "Suriname","suriname": "Suriname",
    "se": "Sweden","swe": "Sweden","sweden": "Sweden",
    "ch": "Switzerland","che": "Switzerland","switzerland": "Switzerland",
    "sy": "Syria","syr": "Syria","syria": "Syria",
    "tw": "Taiwan","twn": "Taiwan","taiwan": "Taiwan",
    "tj": "Tajikistan","tjk": "Tajikistan","tajikistan": "Tajikistan",
    "tz": "Tanzania","tza": "Tanzania","tanzania": "Tanzania",
    "th": "Thailand","tha": "Thailand","thailand": "Thailand",
    "tl": "Timor-Leste","tls": "Timor-Leste","east timor": "Timor-Leste",
    "tg": "Togo","tgo": "Togo","togo": "Togo",
    "to": "Tonga","ton": "Tonga","tonga": "Tonga",
    "tt": "Trinidad and Tobago","tto": "Trinidad and Tobago","trinidad and tobago": "Trinidad and Tobago",
    "tn": "Tunisia","tun": "Tunisia","tunisia": "Tunisia",
    "tr": "Turkey","tur": "Turkey","türkiye": "Turkey","turkiye": "Turkey",
    "tm": "Turkmenistan","tkm": "Turkmenistan","turkmenistan": "Turkmenistan",
    "tc": "Turks and Caicos Islands","tca": "Turks and Caicos Islands",
    "tv": "Tuvalu","tuv": "Tuvalu","tuvalu": "Tuvalu",
    "ug": "Uganda","uga": "Uganda","uganda": "Uganda",
    "ua": "Ukraine","ukr": "Ukraine","ukraine": "Ukraine",
    "ae": "United Arab Emirates","are": "United Arab Emirates","united arab emirates": "United Arab Emirates",
    "gb": "United Kingdom","gbr": "United Kingdom","united kingdom": "United Kingdom","great britain": "United Kingdom",
    "us": "USA","usa": "USA","america": "USA","united states": "USA","united states of america": "USA",
    "uy": "Uruguay","ury": "Uruguay","uruguay": "Uruguay",
    "uz": "Uzbekistan","uzb": "Uzbekistan","uzbekistan": "Uzbekistan",
    "vu": "Vanuatu","vut": "Vanuatu","vanuatu": "Vanuatu",
    "ve": "Venezuela","ven": "Venezuela","venezuela": "Venezuela",
    "vn": "Vietnam","vnm": "Vietnam","vietnam": "Vietnam",
    "ye": "Yemen","yem": "Yemen","yemen": "Yemen",
    "zm": "Zambia","zmb": "Zambia","zambia": "Zambia",
    "zw": "Zimbabwe","zwe": "Zimbabwe","zimbabwe": "Zimbabwe"
};

// ============================================================================
// universal normalization
// ============================================================================
export function normalizeCountry(raw) {
    if (!raw) return null;

    let key = raw.toString()
        .replace(/_/g, " ")
        .replace(/[.,']/g, "")
        .trim()
        .toLowerCase();

    if (ISO_COUNTRY_MAP[key]) return ISO_COUNTRY_MAP[key];

    return key.replace(/\b\w/g, c => c.toUpperCase());

}
